### PR TITLE
Upgrade to helm v2.15.0

### PR DESCRIPTION
**Pull request by chenrui333**
What I Did
------------

Upgrade dependencies:
- helm v2.15.0

How I Did it
------------

For helm upgrade
- `go get helm@v2.15.0`
- `go mod tidy`

How to verify it
------------

Description for the Changelog
------------

Picture of a Ship (not required but encouraged)
------------
Flying ship!

image

### CODE REVIEW

**Comment by laverya** [comment]
I think this needs a run of `go mod vendor`

**Comment by chenrui333** [comment]
Thanks, let's try it!

**Comment by chenrui333** [comment]
I am going to just to have this PR focus on the helm upgrade and have another PR to do the k8s api upgrade (maybe that requires some code changes).

**Comment by chenrui333** [comment]
Not quite sure why a helm-3 PR got slipped into helm 2.15.0. 

PR ref: https://github.com/helm/helm/pull/6032

**Comment by laverya** [comment]
That's really weird - the function signature for sigs.k8s.io/yaml's `Unmarshal` hasn't changed in years: https://github.com/kubernetes-sigs/yaml/blame/master/yaml.go#L35

**Comment by chenrui333** [comment]
The commit, https://github.com/helm/helm/commit/f94bac0643ad5d39c740c57c6c8ea6a4569a1db0#diff-c508e0fda01b39eddfe1d6a4449fe685R109-R112 did make some changes (kind of violating the signature).

**Pull request closed without merging**
