### PR TITLE
wip Upgrade to go v1.13

### PR DESCRIPTION
**Pull request by chenrui333**
What I Did
------------

Upgrade to go v1.13

How I Did it
------------

How to verify it
------------

https://github.com/Homebrew/homebrew-core/pull/44369

Description for the Changelog
------------

Go v1.13 upgrade

Picture of a Ship (not required but encouraged)
------------

### CODE REVIEW

**Comment by laverya** [comment]
There's more than a few issues with upgrading to 1.13, the [last time I looked](https://github.com/laverya/ship/tree/go-1.13) - but perhaps things have gotten better in the intervening weeks. I'll take another look later

**Comment by chenrui333** [comment]
yeah, I did couple golang 1.13 upgrades in the other repos, I think we are in a better shape to also keep `ship` up to date. I will take another look later today. :)

**Comment by laverya** [comment]
Superseded by #1073 - we should be able to deploy to homebrew again with the next ship release

**Comment by chenrui333** [comment]
Sounds good!

**Pull request closed without merging**
